---
- name: Upload tar.gz Kibana from remote URL
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    mode: 0755
    timeout: 60
    force: true
  register: get_kibana
  until: get_kibana is succeeded
  tags: kibana
- name: Create directrory for kibana
  file:
    state: directory
    path: "{{ kibana_home }}"
    mode: 0644
  tags: kibana
- name: Extract Kibana in the installation directory
  become: true
  unarchive:
    copy: false
    src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    dest: "{{ kibana_home }}"
    extra_opts: [--strip-components=1]
    creates: "{{ kibana_home }}/bin/kibana"
  tags:
    - skip_ansible_lint
    - kibana
- name: Set environment Kibana
  become: yes
  template:
    src: templates/kibana.yml.j2
    dest: "{{ kibana_home }}/config/kibana.yml"
    mode: 0644
  tags: kibana
